# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# encoding: utf-8
AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')
AdminUser.create!(email: 'kevin@proyectoalimentar.org', password: 'password', password_confirmation: 'password')
AdminUser.create!(email: 'ignacio@proyectoalimentar.org', password: 'password', password_confirmation: 'password')
AdminUser.create!(email: 'inaki@proyectoalimentar.org', password: 'password', password_confirmation: 'password')
StorageUnit.create!(id:1, name:"San Vicente (Radio Parroquial Inmaculado Corazón de María)", email:"innmaculadocorazondemaria@yahoo.com.ar", telephone:"3880-6821", address:"Constitución 1407", latitude:34.6247456,longitude:-58.3880682,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:2, name:"Casa Madre Teresa (Parroquia Nuestra Sra. De Caacupé)", email:"parroquianuestrasenoradecaacupe@hotmail.com", telephone:"4009-4512", address:"Osvaldo Cruz 3470", latitude:-34.6571221,longitude:-58.4009451,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:3, name:"Hogar Niño Jesús (Parroquia Nuestra Sra. De Caacupé)", email:"parroquianuestrasenoradecaacupe@hotmail.com", telephone:"4009-4512", address:"Osvaldo Cruz 3470", latitude:-34.6571221,longitude:-58.4009451,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:4, name:"Villa 21 - Merendero (Parroquia Nuestra Sra. De Caacupé)", email:"parroquianuestrasenoradecaacupe@hotmail.com", telephone:"4009-4513", address:"Osvaldo Cruz 3470", latitude:-34.6571221,longitude:-58.4009451,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:5, name:"Mamá Margarita (Parroquia San Juan Evangelista)", email:"sanjuanevangelista@gmail.com", telephone:"5004-3894", address:"Olavarria 486", latitude:-34.6602706,longitude:-58.5004389,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:6, name:"Mons. Jaime de Nevares (Parroquia Santa Catalina de Alejandría)", email:"santacatalinadealejandria@hotmail.com", telephone:"3783-0425", address:"Piedras 1527", latitude:-34.6264521,longitude:-58.3783042,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:7, name:"Santa Elisa (Parroquia Santa Elisa)", email:"parroquiasantaelisa@gmail.com", telephone:"3846-0256", address:"Salta 2290", latitude:-34.6338553,longitude:-58.3846025,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:8, name:"Inmaculada Concepción (Parroquia Inmaculada Concepción - Centro)", email:"inmaculadaconcepcion@gmail.com", telephone:"3808-9832", address:"Tacuarí 870", latitude:-34.6182636,longitude:-58.380898,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:9, name:"Olla Solidaria Multisectorial (Parroquia Santa Cruz)", email:"parroquiasantacruz@yahoo.com.ar", telephone:"4823-8943", address:"Estados Unidos 3150", latitude:-34.6616911,longitude:-58.4823894,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:10, name:"Hogar Comedor San José (Radio Parroquial Santa Rosa de Lima)", email:"parroquiasantarosadelima@hotmail.com", telephone:"5434-1462", address:"Moreno 2472", latitude:-34.6370999,longitude:-58.5434146,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:11, name:"Santa Rosa (Parroquia Santa Rosa de Lima)", email:"santa.rosa.parroquia@gmail.com", telephone:"5479-3311", address:"Pasco 436", latitude:-34.6345002,longitude:-58.5479331,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:12, name:"PASO - Iglesia Anglicana (Radio Parroquial Ntra. Sra. De La Merced)", email:"iglesia.anglicana.paso@gmail.com", telephone:"6473-8241", address:"25 de Mayo 282", latitude:-34.6210903,longitude:-58.6473824,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:13, name:"Mons. Albisetti (Parroquia Ntra. Sra. Del Socorro)", email:"nuestra.senora.del.socorro@yahoo.com.ar", telephone:"5538-0879", address:"Suipacha 1363", latitude:-34.5868389,longitude:-58.5538087,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:14, name:"La Tacita - Primera Iglesia Metodista (Radio Parroquial San Miguel Arcángel)", email:"parroquial.san.miguel.arcangel@hotmail.com", telephone:"3792-7627", address:"Av. Corrientes 718", latitude:-34.6036674,longitude:-58.3792762,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:15, name:"San Nicolás de Bari (Parroquia San Nicolás de Bari)", email:"san.nicolas.bari@gmail.com", telephone:"3887-6061", address:"Av. Santa Fe 1352", latitude:-34.5958276,longitude:-58.3887606,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:16, name:"Centro San José (De la Parroquia Ntra. Sra. De Caacupé - Barracas)", email:"nuestra.senora.de.caacupe@gmail.com", telephone:"4121-5254", address:"Ventana 3499", latitude:-34.6498102,longitude:-58.4121525,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:17, name:"Patrocinio de la Virgen (Parroquia Patrocinio de la Virgen)", email:"parroquia.patrocinio.de.la.virgen@gmail.com", telephone:"4121-7397", address:"24 de noviembre 1651", latitude:-34.6304307,longitude:-58.4121739,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:18, name:"San Lorenzo (Parroquia San Lorenzo Mártir)", email:"parroquiasanlorenzo@gmail.com", telephone:"4306-1086", address:"Avelino Díaz 576", latitude:-34.6354499,longitude:-58.4306108,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:19, name:"Nuestra Señora de Balvanera (Parroquia Ntra. Sra. De Balvanera)", email:"nuestrasenoradebalvanera@hotmail.com", telephone:"4032-0369", address:"Bartolomé Mitre 2431", latitude:-34.6084916,longitude:-58.4032036,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:20, name:"Nuestra Señora de Caacupé (Parroquia Ntra. Sra. De Caacupé - Av. Rivadavia)", email:"nuestrasenoradecaacupe@gmail.com", telephone:"4360-8333", address:"Av. Rivadavia 4879", latitude:-34.617138,longitude:-58.4360833,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:21, name:"Fundación Judaica Emanuel (Radio Parroquial Ntra. Sra. De Fátima)", email:"fundacionjudaicaemanuel@gmail.com", telephone:"4578-3042", address:"Arcos 2319", latitude:-34.5582809,longitude:-58.4578304,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:22, name:"Inmaculada Concepción (Parroquia Inmaculada Concepción - Belgrano)", email:"inmaculada.concepcion.belgrano@hotmail.com", telephone:"4573-8721", address:"Vuelta de Obligado 2042", latitude:-34.5619959,longitude:-58.457387,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:23, name:"La Virgen y La Escobita (Parroquia Ntra. Sra. De Luján Castrense)", email:"nuestra.senora.de.lujan@gmail.com", telephone:"4429-8662", address:"Av. Cabildo 405", latitude:-34.5720691,longitude:-58.4429866,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:24, name:"Santísima Trinidad (Parroquia Santísima Trinidad)", email:"parroquia.santisima.trinidad@gmail.com", telephone:"4703-9152", address:"Av. Cabildo 3680", latitude:-34.5493871,longitude:-58.4703915,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:25, name:"Santo Tomás de Villanueva (Parroquia Ntra. Sra. De La Consolación)", email:"santo.tomas.de.villanueva@gmail.com", telephone:"4326-9032", address:"Jufré 148", latitude:-34.5977828,longitude:-58.4326903,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:26, name:"El Peregrino (Iglesia Corazón Eucarístico de Jesús)", email:"el.peregrino@hotmail.com", telephone:"3924-4571", address:"Montevideo 1372", latitude:-34.5936296,longitude:-58.3924457,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:27, name:"Santa Elena (Parroquia Santa Elena)", email:"parroquia.santa.elena@gmail.com", telephone:"4144-7132", address:"Lafinur 3331", latitude:-34.5772092,longitude:-58.414471,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:28, name:"Madre Camila (Parroquia Santísimo Redentor)", email:"parroquia.santisimo.redentor@hotmail.com", telephone:"4025-2721", address:"Larrea 1252", latitude:-34.5927356,longitude:-58.4025527,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:29, name:"Virgen de Guadalupe (Parroquia Ntra. Sra. De Guadalupe)", email:"virgen.de.guadalupe.parroquia@gmail.com", telephone:"4203-4032", address:"Guatemala 4059", latitude:-34.5896235,longitude:-58.4203403,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:30, name:"Cura Brochero (Parroquia Ntra. Sra. De La Misericordia)", email:"nuestra.senora.de.la.misericordia@gmail..com", telephone:"4932-9482", address:"Av. Larrazábal 2390", latitude:-34.661297,longitude:-58.4932948,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:31, name:"Nuestra Sra. De La Paz", email:"nuestra.senora.de.la.paz@gmail.com", telephone:"4763-8596", address:"Pergamino 63", latitude:-34.6329498,longitude:-58.4763859,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:32, name:"San José de Flores (Parroquia San José de Flores)", email:"sanjosedeflores@gmail.com", telephone:"4653-3274", address:"Salalá 60", latitude:-34.6298896,longitude:-58.4653327,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:33, name:"Santa Clara (Parroquia Santa Clara)", email:"santaclara@hotmail.com", telephone:"4581-7018", address:"Zuviría 2631", latitude:-34.6426624,longitude:-58.4581701,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:34, name:"Santa Julia (Parroquia Santa Julia)", email:"psantajulia@hotmail.com", telephone:"4472-3734", address:"Av. Juan Bautista Alberdi 1195", latitude:-34.6233925,longitude:-58.4472373,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);
StorageUnit.create!(id:35, name:"Medalla Milagrosa (Parroquia Ntra. Sra. De la Medalla Milagrosa)", email:"secretaria_medallamilagrosa@yahoo.com.ar", telephone:"4481-8279", address:"Curapaligue 1185", latitude:-34.6364811,longitude:-58.4481827,service_time_from:"9",service_time_to:"18", created_at:DateTime.now, updated_at:DateTime.now);

ProductType.create!(id:1 , name: "Hamburguesa Congelada Express Paty x 4 Un x 274 Gr BRF", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:2 , name: "Medallón de Carne Vacuna Clásico Supercongelado Swift 4 Un x 276 Gr JBS", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:3 , name: "Adobo para Pizza Sobre La Parmesana x 25 Gr POO ALIMENTOS S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:4 , name: "Ají Molido Sobre La Parmesana x 50 Gr POO ALIMENTOS S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:5 , name: "Alimento a Base de Miel Granja Rosalía x 500 Gr SANCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:6 , name: "Arroz Largo Fino 0000 Lucchetti x 500 Gr MOLINOS RIO DE LA PLATA", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:7 , name: "Arroz Largo Fino 00000 Molinos Ala x 500 Gr ADECO AGRO", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:8 , name: "Arroz Largo Fino Integral 00000 Noble Molinos Entrerrianos x 1 Kg COOP.", expiration_time: 10, measurement_unit: "Kg", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:9 , name: "Arvejas 7 Días x 350 Gr RPB", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:10 , name: "Arvejas Secas Remojadas Lata Arcor x 300 Gr ARCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:11 , name: "Arvejas Tetra Recart Molto x 340 Gr MAROLIO S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:12 , name: "Atún al Natural Supremacía x 170 Gr SUPREMACÍA MARINA", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:13 , name: "Atún en Aceite Supremacía x 170 Gr SUPREMACÍA MARINA", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:14 , name: "Azúcar Molida Clásica Bolsa Ledesma x 1 Kg LEDESMA", expiration_time: 10, measurement_unit: "Kg", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:15 , name: "Caballa al Natural La Gallega x 380 Gr COPECA S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:16 , name: "Caballa al Natural Marechiare x 380 Gr CENTAURO S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:17 , name: "Caballa al Natural Puglisi x 380 Gr COPECA S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:18 , name: "Caballa al Natural Supremacia x 380 Gr SUPREMACÍA MARINA", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:19 , name: "Caballa en Aceite La Gallega x 380 Gr COPECA S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:20 , name: "Caballa en Aceite Marechiare x 380 Gr CENTAURO S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:21 , name: "Caballa en Aceite Mellino x 380 Gr NATUSUR S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:22 , name: "Caballa en Aceite Puglisi x 380 Gr COPECA S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:23 , name: "Caballa en Aceite Supremacia x 380 Gr SUPREMACÍA MARINA", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:24 , name: "Caballa Mellino al Natural x 380 Gr NATUSUR S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:25 , name: "Caballa Pennisi al Natural x 380 Gr NATUSUR S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:26 , name: "Caballa Pennisi en Aceite x 380 Gr NATUSUR S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:27 , name: "Cacao en Polvo Arcor x 360 Gr ARCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:28 , name: "Café Instantáneo en Frasco de Vidrio La Morenita x 100 Gr LA VIRGINIA", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:29 , name: "Calamares en Aceite Supremacia x 170 Gr SUPREMACÍA MARINA", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:30 , name: "Condimento para Arroz sobre La Parmesana x 25 Gr POO ALIMENTOS S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:31 , name: "Dulce de Batata Light Emeth Bandeja x 480Gr DULFIX", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:32 , name: "Dulce de Batata Vainilla Caroyense x 500 Gr CAROYENSE", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:33 , name: "Dulce de Membrillo Arcor Estuche x 500 Gr ARCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:34 , name: "Dulce de Membrillo Light Emeth Bandeja x 480Gr DULFIX", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:35 , name: "Edulcorante en sobre con Aspartamo La Virginia x 100 Un LA VIRGINIA", expiration_time: 10, measurement_unit: "Un", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:36 , name: "Gelatina Cereza BC x 30 Gr ARCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:37 , name: "Harina de Trigo 000 Cañuelas x 1 Kg MOLINO CAÑUELAS", expiration_time: 10, measurement_unit: "Kg", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:38 , name: "Harina de Trigo 000 Caserita x 1 Kg LAGOMARSINO SA", expiration_time: 10, measurement_unit: "Kg", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:39 , name: "Harina de Trigo 0000 Blancaflor x 1 Kg MOLINOS RIO DE LA PLATA", expiration_time: 10, measurement_unit: "Kg", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:40 , name: "Jardinera en Lata 7 Días Baggio x 350 Cc RPB", expiration_time: 10, measurement_unit: "Cc", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:41 , name: "Jugo de Limón Comensal x 1000 Cc FRADEALCO S.A", expiration_time: 10, measurement_unit: "Cc", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:42 , name: "Jugo de Limón Comensal x 500 Cc FRADEALCO S.A", expiration_time: 10, measurement_unit: "Cc", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:43 , name: "Jugo de Limón La Parmesana x 500 Cc POO ALIMENTOS S.A.", expiration_time: 10, measurement_unit: "Cc", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:44 , name: "Mate Cocido en Saquitos Cachamate x 25 Un CACHAY S.A.", expiration_time: 10, measurement_unit: "Un", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:45 , name: "Mayonesa Light BC La Campagnola Doy Pack x 500 Gr ARCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:46 , name: "Merluza al Natural Puglisi x 380 Gr COPECA S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:47 , name: "Merluza al Natural Supremacía x 380 Gr SUPREMACÍA MARINA", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:48 , name: "Merluza en Aceite Pennisi x 380 Gr NATUSUR S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:49 , name: "Merluza en Aceite Puglisi x 380 Gr COPECA S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:50 , name: "Merluza en Agua y Aceite Marechiare x 380 Gr CENTAURO S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:51 , name: "Mermelada de Ciruela en Frasco Arcor x 454 Gr ARCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:52 , name: "Mermelada de Durazno Frasco Dulcor x 454 Gr DULCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:53 , name: "Mermelada de Durazno Light Frasco Arcor x 390 Gr ARCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:54 , name: "Mermelada Durazno Favaloro Caroyense Frasco x 454 Gr CAROYENSE", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:55 , name: "Mermelada Durazno Light Favaloro Caroyense Frasco x 390 Gr CAROYENSE", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:56 , name: "Mermelada Frutilla Favaloro Caroyense Frasco x 454 Gr CAROYENSE", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:57 , name: "Mermelada Frutilla Light Favaloro Caroyense Frasco x 390 Gr CAROYENSE", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:58 , name: "Mix de Cereales sobre La Parmesana x 100 Gr POO ALIMENTOS S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:59 , name: "Óregano Bolsa La Parmesana x 25 Gr POO ALIMENTOS S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:60 , name: "Pan de Mesa Lacteado Lactal x 380 Gr GRUPO BIMBO", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:61 , name: "Pan de Salvado Doble Rebanado sin Sal Fargo x 400 Gr GRUPO BIMBO", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:62 , name: "Pan para Hamburguesas Lactal x 216 Gr GRUPO BIMBO", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:63 , name: "Pan para Panchos Lactal x 216 Gr GRUPO BIMBO", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:64 , name: "Pan Rallado Plus Mama Cocina x 1 Kg MOLINO CAÑUELAS", expiration_time: 10, measurement_unit: "Kg", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:65 , name: "Pan Rallado Vita K Caserita x 1 Kg LAGOMARSINO SA", expiration_time: 10, measurement_unit: "Kg", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:66 , name: "Pasas de Uva sin Semilla Bolsa La Parmesana x 250 Gr POO ALIMENTOS S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:67 , name: "Polenta Fortificada del Campo x 400 Gr RIVARA S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:68 , name: "Polenta Instantánea del Campo x 500 Gr RIVARA S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:69 , name: "Polenta Instantánea Prestopronta Arcor x 750 Gr ARCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:70 , name: "Puré de Tomate Listo Baggio De La Huerta x 530 Gr RPB", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:71 , name: "Puré de Tomate Tetra Brick Molto x 360 Gr MAROLIO S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:72 , name: "Puré de Tomate Tetra Brik Caroyense x 520 Gr CAROYENSE", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:73 , name: "Sal Entrefina Estuche Dos Anclas x 500 Gr CIA.INTRODUCTORA BS.AS.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:74 , name: "Sal Fina Light Dos Anclas x 500 Gr CIA.INTRODUCTORA", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:75 , name: "Sal sin Sodio Sabor Ajo Sobre La Parmesana x 75 Gr POO ALIMENTOS S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:76 , name: "Sal sin Sodio Sabor Apio Sobre La Parmesana x 75 Gr POO ALIMENTOS S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:77 , name: "Sal sin Sodio Sabor Cebolla Sobre La Parmesana x 75 Gr POO ALIMENTOS S.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:78 , name: "Sal sin Sodio sin Sabor Sobre La Parmesana x 75 Gr POO ALIMENTOS S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:79 , name: "Salsa Pizza de La Huerta x 530 Cc RPB", expiration_time: 10, measurement_unit: "Cc", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:80 , name: "Salsa Pomarola de La Huerta x 530 Cc RPB", expiration_time: 10, measurement_unit: "Cc", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:81 , name: "Salsa Pomarola Salsati Doy Pack x 340 Gr ARCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:82 , name: "Semilla de Chía Sobre La Parmesana x 100 Gr POO ALIMENTOS S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:83 , name: "Té Rosamonte en Saquitos x 25 Un HREÑUK", expiration_time: 10, measurement_unit: "Un", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:84 , name: "Vinagre de Alcohol Comensal x 1000 Cc FRADEALCO S.A", expiration_time: 10, measurement_unit: "Cc", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:85 , name: "Vinagreta La Parmesana x 300 Cc POO ALIMENTOS S.A.", expiration_time: 10, measurement_unit: "Cc", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:86 , name: "Yerba Mate Campo Amanda x 1 Kg LA CACHUERA SA", expiration_time: 10, measurement_unit: "Kg", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:87 , name: "Yerba Mate Campo y Monte Mañanita x 1 Kg ESTABLECIMIENTO LAS MARIAS S.", expiration_time: 10, measurement_unit: "Kg", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:88 , name: "Yerba Mate con Palo Amanda x 1 Kg LA CACHUERA SA", expiration_time: 10, measurement_unit: "Kg", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:89 , name: "Yerba Mate con Palo Romance x 1 Kg GERULA S.A.", expiration_time: 10, measurement_unit: "Kg", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:90 , name: "Yerba Mate con Palo Rosamonte Junior x 500 Gr HREÑUK", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:91 , name: "Yerba Mate con Palo Selección Especial La Tranquera x 1 Kg LLORENTE", expiration_time: 10, measurement_unit: "Kg", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:92 , name: "Yerba Mate con Palo Selección Especial La Tranquera x 500 Gr LLORENTE ", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:93 , name: "Yerba Mate Liviana Taraguí x 1 Kg ESTABLECIMIENTO LAS MARIAS S.A.", expiration_time: 10, measurement_unit: "Kg", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:94 , name: "Yerba Mate Rosamonte Junior x 1 Kg HREÑUK", expiration_time: 10, measurement_unit: "Kg", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:95 , name: "Yerba Mate Suave Nobleza Gaucha x 500 Gr MOLINOS RIO DE LA PLATA", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:96 , name: "Yerba Mate Suave Romance x 1 Kg GERULA S.A.", expiration_time: 10, measurement_unit: "Kg", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:97 , name: "Agua Mineral sin Gas Bidón Kin x 6 Lt COCA COLA", expiration_time: 10, measurement_unit: "Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:98 , name: "Agua Mineral sin Gas Bonaqua x 2 Lt COCA COLA", expiration_time: 10, measurement_unit: "Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:99 , name: "Agua Mineral sin Gas Botella Kin x 2 Lt COCA COLA", expiration_time: 10, measurement_unit: "Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:100 , name: "Agua Mineral sin Gas Kin x 2.25 Lt COCA COLA", expiration_time: 10, measurement_unit: "2.Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:101 , name: "Agua Mineralizada sin Gas Cellier Favaloro x 2 Lt PRODEA", expiration_time: 10, measurement_unit: "Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:104 , name: "Agua Saborizada Naranja Cellier Favaloro x 1.5 Lt PRODEA", expiration_time: 10, measurement_unit: "1.Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:105 , name: "Agua Saborizada Naranja Durazno Cellier Favaloro x 1.5 Lt PRODEA", expiration_time: 10, measurement_unit: "1.Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:107 , name: "Alimento con Vit C sin Gas Vida By Baggio Naranja Dulce x 1500 Cc RPB", expiration_time: 10, measurement_unit: "Cc", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:108 , name: "Alimento con Vit C sin Gas Vida By Baggio Pera x 1500 Cc RPB", expiration_time: 10, measurement_unit: "Cc", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:109 , name: "Alimento con Vit C sin Gas Vida By Baggio Pomelo x 1500 Cc RPB", expiration_time: 10, measurement_unit: "Cc", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:110 , name: "Alimento con Vitamina C sin Gas Sabor Manzana Baggio Vida x 500 Cc RPB", expiration_time: 10, measurement_unit: "Cc", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:111 , name: "Alimento con Vitamina C sin Gas Sabor Naranja Baggio Vida 500 Cc RPB", expiration_time: 10, measurement_unit: "Cc", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:112 , name: "Alimento con Vitamina C sin Gas Sabor Pomelo Baggio Vida x 500 Cc RPB", expiration_time: 10, measurement_unit: "Cc", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:113 , name: "Alimento Multifruta Ades x 330 Cc UNILEVER", expiration_time: 10, measurement_unit: "Cc", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:114 , name: "Gaseosa Coca Cola Zero x 1.5 Lt COCA COLA", expiration_time: 10, measurement_unit: "1.Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:115 , name: "Gaseosa Cunnington Cola x 1.50 Lt PRODEA", expiration_time: 10, measurement_unit: "1.Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:116 , name: "Gaseosa Cunnington Cola x 2.25 Lt PRODEA", expiration_time: 10, measurement_unit: "2.Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:117 , name: "Gaseosa Cunnington Lima Limón x 1.50 Lt PRODEA", expiration_time: 10, measurement_unit: "1.Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:118 , name: "Gaseosa Cunnington Lima Limón x 2.25 Lt PRODEA", expiration_time: 10, measurement_unit: "2.Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:119 , name: "Gaseosa Fanta Naranja Zero Vitamina C Botella x 1.5 Lt COCA COLA", expiration_time: 10, measurement_unit: "1.Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:120 , name: "Gaseosa Mirinda Naranja x 1.5 Lt CERVECERIA Y MALTERIA QUILMES", expiration_time: 10, measurement_unit: "1.Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:121 , name: "Gaseosa Mocoretá Cola x 2.25 Lt RPB", expiration_time: 10, measurement_unit: "2.Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:122 , name: "Gaseosa Mocoretá Lima Limón x 2.25 Lt RPB", expiration_time: 10, measurement_unit: "2.Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:123 , name: "Gaseosa Mocoretá Naranja x 2.25 Lt RPB", expiration_time: 10, measurement_unit: "2.Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:124 , name: "Gaseosa Pepsi Light x 1.5 Lt CERVECERIA Y MALTERIA QUILMES", expiration_time: 10, measurement_unit: "1.Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:125 , name: "Gaseosa Sprite Zero x 1.5 Lt COCA COLA", expiration_time: 10, measurement_unit: "1.Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:126 , name: "Jugo Baggio Fresh Durazno Tetrabrik x 1000 Cc RPB", expiration_time: 10, measurement_unit: "Cc", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:127 , name: "Jugo Baggio Fresh Manzana Deliciosa Tetrabrik x 1000 Cc RPB", expiration_time: 10, measurement_unit: "Cc", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:128 , name: "Jugo Baggio Fresh Manzana Deliciosa Tetrabrik x 200 Ml RPB", expiration_time: 10, measurement_unit: "Ml", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:129 , name: "Jugo Baggio Fresh Multifruta Tetrabrik x 1000 Cc RPB", expiration_time: 10, measurement_unit: "Cc", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:130 , name: "Jugo Baggio Fresh Multifruta Tetrabrik x 200 Ml RPB", expiration_time: 10, measurement_unit: "Ml", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:131 , name: "Jugo Baggio Fresh Naranja Dulce Tetrabrik x 1000 Cc RPB", expiration_time: 10, measurement_unit: "Cc", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:132 , name: "Jugo Light Baggio Fresh Naranja Dulce Tetrabrik x 200 Ml RPB", expiration_time: 10, measurement_unit: "Ml", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:133 , name: "Jugo Líquido Naranja BC La Campagnola x 1 Lt ARCOR", expiration_time: 10, measurement_unit: "Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:134 , name: "Soda en Botella Kin x 2 Lt COCA COLA", expiration_time: 10, measurement_unit: "Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:135 , name: "Cintitas Crocantes Agridulces Tostex x 125 Gr TOSTEX S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:136 , name: "Cintitas Crocantes con Semillas Tostex x 125 Gr TOSTEX S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:137 , name: "Cintitas Crocantes Light Tostex x 125 Gr TOSTEX S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:138 , name: "Cintitas Crocantes Sabor Cebolla Tostex x 125 Gr TOSTEX S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:139 , name: "Cintitas Crocantes Tostex Clásica x 125 Gr TOSTEX S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:140 , name: "Cintitas Crocantes Tostex Queso x 125 Gr TOSTEX S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:141 , name: "Galletitas Chips Tubo Tostex x 90 Gr TOSTEX S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:142 , name: "Galletitas Clásicas Express x 108 Gr MONDELEZ ", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:143 , name: "Galletitas Clásicas Mediatarde x 110 Gr ARCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:144 , name: "Galletitas con Semillas Molino Natural Okebon x 255 Gr ALICORP", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:145 , name: "Galletitas Confites Tubo Tostex x 90 Gr TOSTEX S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:146 , name: "Galletitas Marias Chocolate Okebon x 145 Gr ALICORP", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:147 , name: "Galletitas Marias Okebon Vainilla x 145 Gr ALICORP", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:148 , name: "Galletitas Panal Vainilla Fortiplus Okebon x 280 Gr ALICORP", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:149 , name: "Galletitas Sabor Chocolate Rellena Vainilla Macucas x 123 Gr ARCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:150 , name: "Galletitas Vainilla Vocación Clásicas Pack x 3 Un x 465 Gr ARCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:151 , name: "Mini Cracker Cinco Semillas Paseo x 150 Gr MOLINO CAÑUELAS", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:152 , name: "Mini Cracker Clásica Paseo x 150 Gr MOLINO CAÑUELAS", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:153 , name: "Mini Cracker Con Salvado Paseo x 150 Gr MOLINO CAÑUELAS", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:154 , name: "Mini Cracker Sésamo Paseo x 150 Gr MOLINO CAÑUELAS", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:155 , name: "Dulce de Leche Familiar Yatasto x 400 Gr LÁCTEOS YATASTO", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:156 , name: "Dulce de Leche Repostero Yatasto x 400 Gr LÁCTEOS YATASTO", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:157 , name: "Dulce de Leche Sandy x 400 Gr RPB", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:158 , name: "Flan de Vainilla con Caramelo Danette Pack x 2 Un x 190 Gr DANONE", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:159 , name: "Flan de Vainilla Ser Pack 2 Un x 190 Gr DANONE", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:160 , name: "Flan Dulce de Leche Danette Pack x 2 Un x 190 Gr DANONE", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:161 , name: "Flan Vainilla con Caramelo Ilolay Kids x 110 Gr WILLINNER", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:162 , name: "Flan Vainilla con Dulce de Leche Ilolay Kids x 110 Gr WILLINNER", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:163 , name: "Flan Vainilla Fortificado Serenito Pack 2 Un x 210 Gr DANONE", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:164 , name: "Gelatina Frutilla Yatasto x 95 Gr LÁCTEOS YATASTO", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:165 , name: "Gelatina Manzana Yatasto x 95 Gr LÁCTEOS YATASTO", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:166 , name: "Leche Chocolatada 7 Días Baggio x 1000 Cc RPB", expiration_time: 10, measurement_unit: "Cc", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:167 , name: "Leche Chocolatada 7 Días Baggio x 200 Cc RPB", expiration_time: 10, measurement_unit: "Cc", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:168 , name: "Leche Chocolatada en Polvo Instantánea Nido x 360 Gr NESTLÉ ARGENTINA ", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:169 , name: "Leche Chocolatada Sachet La Suipachense x 1 Lt LACTEOS CONOSUR SA", expiration_time: 10, measurement_unit: "Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:170 , name: "Leche Chocolatada Semidescremada UHT Sandy by Baggio x 1000 Cc RPB", expiration_time: 10, measurement_unit: "Cc", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:171 , name: "Leche Chocolatada Semidescremada UHT Sandy by Baggio x 200 Cc RPB", expiration_time: 10, measurement_unit: "Cc", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:172 , name: "Leche Chocolatada Shimy UAT Tetra Sancor x 1 Lt SANCOR", expiration_time: 10, measurement_unit: "Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:173 , name: "Leche en Polvo Descremada Fortificada Sancor x 400 Gr SANCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:174 , name: "Leche Entera Baggio Latte Kids x 1000 Cc RPB", expiration_time: 10, measurement_unit: "Cc", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:175 , name: "Leche Entera Baggio Latte Kids x 200 Cc RPB", expiration_time: 10, measurement_unit: "Cc", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:176 , name: "Leche Entera en Polvo Instantánea Purísima x 400 Gr SA LA SIBILA", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:177 , name: "Leche Entera Larga Vida con Calcio UAT La Lacteo x 1 Lt LA LACTEO SA", expiration_time: 10, measurement_unit: "Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:178 , name: "Leche Entera Larga Vida Fortificada 7 Días x 1 Lt RPB", expiration_time: 10, measurement_unit: "Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:179 , name: "Leche Entera Sachet Santa Brígida x 1 Lt SANCOR", expiration_time: 10, measurement_unit: "Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:180 , name: "Leche Entera UAT Las Tres Niñas x 1 Lt SANCOR", expiration_time: 10, measurement_unit: "Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:181 , name: "Leche Entera UAT Verónica x 1 Lt VERÓNICA S.A.", expiration_time: 10, measurement_unit: "Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:183 , name: "Leche Parcialmente Descremada Sachet Santa Brígida x 1 Lt SANCOR", expiration_time: 10, measurement_unit: "Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:184 , name: "Leche Parcialmente Descremada UAT Las Tres Niñas x 1 Lt SANCOR", expiration_time: 10, measurement_unit: "Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:185 , name: "Postre Chocolate Danette Pack 4 Un x 380 Gr DANONE", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:186 , name: "Postre de Chocolate con Dulce de Leche Shimy x 120 Gr SANCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:187 , name: "Postre de Chocolate Crash Serenito Pack x 2 Un x 200 Gr DANONE", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:188 , name: "Postre de Chocolate Shimy x 120 Gr SANCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:189 , name: "Postre de Vainilla con Dulce de Leche Shimy x 120 Gr SANCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:190 , name: "Postre de Vainilla Crash Serenito Pack x 2 Un x 200 Gr DANONE", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:191 , name: "Postre de Vainilla Shimy x 120 Gr SANCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:192 , name: "Postre Dulce de Leche Danette Pack 4 Un x 380 Gr DANONE", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:193 , name: "Postre Dulce de Leche Shimy x 120 Gr SANCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:194 , name: "Postre Niño Sabor Frutilla Yatasto x 100 Gr LÁCTEOS YATASTO", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:195 , name: "Postre Yatasto Vainilla x 100 Gr LÁCTEOS YATASTO", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:196 , name: "Queso Blanco Cremoso Mendicrim x 300 Gr SANCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:197 , name: "Queso Blanco Light Casancrem x 500 Gr DANONE", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:198 , name: "Queso Crema Clásico Casancrem x 500 Gr DANONE", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:199 , name: "Queso Crema Yatasto x 200 Gr LÁCTEOS YATASTO", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:200 , name: "Queso Cremoso Cuartirolo La Suipachense x 1 Kg LACTEOS CONOSUR SA", expiration_time: 10, measurement_unit: "Kg", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:201 , name: "Queso Port Salut La Suipachense x 1 Kg LACTEOS CONOSUR SA", expiration_time: 10, measurement_unit: "Kg", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:202 , name: "Queso Rallado Santa Brígida x 120 Gr SANCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:203 , name: "Queso Untable Fundido Light Port Salut Sancor x 190 Gr SANCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:204 , name: "Queso Untable Sabor Clásico Verónica x 190 Gr VERÓNICA S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:205 , name: "Quesos Port Salut Tradicional Light Trozado Sancor x 1 Kg SANCOR", expiration_time: 10, measurement_unit: "Kg", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:211 , name: "Yogur Descremado Bebible Frutilla Sachet Milkaut x 1 Kg MILKAUT", expiration_time: 10, measurement_unit: "Kg", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:212 , name: "Yogur Descremado Bebible Frutilla Sancor Yogs x 185 Gr SANCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:213 , name: "Yogur Descremado Bebible Multifruta Ser x 185 Gr DANONE", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:214 , name: "Yogur Descremado Bebible Vainilla Sachet Milkaut x 1 Kg MILKAUT", expiration_time: 10, measurement_unit: "Kg", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:215 , name: "Yogur Descremado Bebible Vainilla Sancor Yogs x 185 Gr SANCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:216 , name: "Yogur Descremado con Cereales Sancor Yogs x 162 Gr SANCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:217 , name: "Yogur Descremado Frutilla Yatasto x 1 Lt LÁCTEOS YATASTO", expiration_time: 10, measurement_unit: "Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:218 , name: "Yogur Descremado Multinutrientes Durazno Sancor Yogs x 180 Gr SANCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:220 , name: "Yogur Descremado Multinutrientes Frutado Sancor Yogs x 180 Gr SANCOR", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:221 , name: "Yogur Descremado Vainilla Yatasto x 1 Lt LÁCTEOS YATASTO", expiration_time: 10, measurement_unit: "Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:222 , name: "Yogur Entero Bebible Durazno La Suipachense x 1 Lt LACTEOS CONOSUR SA", expiration_time: 10, measurement_unit: "Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:223 , name: "Yogur Entero Bebible Frutilla La Suipachense x 1 Lt LACTEOS CONOSUR SA", expiration_time: 10, measurement_unit: "Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:224 , name: "Yogur Entero Bebible Frutilla Yogurísimo x 185 Gr DANONE", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:226 , name: "Yogur Entero Bebible Tutifruti La Suipachense x 1 Lt LACTEOS CONOSUR SA", expiration_time: 10, measurement_unit: "Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:227 , name: "Yogur Entero Bebible Vainilla en Botella Yogurísimo x 185 Gr DANONE", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:228 , name: "Yogur Entero Bebible Vainilla La Suipachense x 1 Lt LACTEOS CONOSUR SA", expiration_time: 10, measurement_unit: "Lt", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:230 , name: "Yogur Vainilla con Aritos Frutados Ilolay x 160 Gr WILLINNER", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:232 , name: "Fideos de Sémola Molto de Trigo Candeal Tirabuzón x 500 Gr MAROLIO S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:236 , name: "Fideos Mostachol Rayado Molto x 500 Gr MAROLIO S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:237 , name: "Fideos Mostachol Rayado Nutri+ Nutregal x 500 Gr ALICORP", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:238 , name: "Fideos Mostacholes Manera x 500 Gr MOLINOS RIO DE LA PLATA", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:239 , name: "Fideos Secos Codito San Agustín x 500 Gr MOLINO CAÑUELAS", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:240 , name: "Fideos Secos con Cúrcuma Marolio Mostachol Liso x 500 Gr MAROLIO S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:241 , name: "Fideos Secos San Agustín Tirabuzón x 500 Gr MOLINO CAÑUELAS", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:242 , name: "Fideos Secos Spaghetti Marolio x 500 Gr MAROLIO S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:243 , name: "Fideos Spaghetti Molto x 500 Gr MAROLIO S.A.", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:244 , name: "Fideos Spaghetti Nutri+ Nutregal x 500 Gr ALICORP", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:245 , name: "Fideos Spaghettis Frescos al huevo La Salteña x 500 Gr LA SALTEÑA SA", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:247 , name: "Fideos Tallarín Fortificado Favorita x 500 Gr MOLINOS RIO DE LA PLATA", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:248 , name: "Fideos Tallarín Manera x 500 Gr MOLINOS RIO DE LA PLATA", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:251 , name: "Tapa Pascualina Light La Salteña 2 x 400 Gr LA SALTEÑA SA", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
ProductType.create!(id:252 , name: "Tapas para Empanadas Hojaldre Fargo 16 Unidades x 453 Gr GRUPO BIMBO", expiration_time: 10, measurement_unit: "Gr", created_at: Time.now, updated_at: Time.now)
BarCode.create!(code: "7790670050766", amount: 1, product_type_id: 1)
BarCode.create!(code: "7790360966841", amount: 1, product_type_id: 2)
BarCode.create!(code: "7796373002286", amount: 1, product_type_id: 3)
BarCode.create!(code: "7796373002293", amount: 1, product_type_id: 4)
BarCode.create!(code: "7790080055023", amount: 1, product_type_id: 5)
BarCode.create!(code: "7790070412614", amount: 1, product_type_id: 6)
BarCode.create!(code: "7791120031564", amount: 1, product_type_id: 7)
BarCode.create!(code: "7790203000336", amount: 1, product_type_id: 8)
BarCode.create!(code: "7790036007687", amount: 1, product_type_id: 9)
BarCode.create!(code: "7790580982102", amount: 1, product_type_id: 10)
BarCode.create!(code: "7798138552838", amount: 1, product_type_id: 11)
BarCode.create!(code: "7790261012005", amount: 1, product_type_id: 12)
BarCode.create!(code: "7790261010001", amount: 1, product_type_id: 13)
BarCode.create!(code: "7792540260138", amount: 1, product_type_id: 14)
BarCode.create!(code: "7790748010043", amount: 1, product_type_id: 15)
BarCode.create!(code: "7798003225515", amount: 1, product_type_id: 16)
BarCode.create!(code: "7790748235095", amount: 1, product_type_id: 17)
BarCode.create!(code: "7790261032010", amount: 1, product_type_id: 18)
BarCode.create!(code: "7790748010036", amount: 1, product_type_id: 19)
BarCode.create!(code: "7798003220336", amount: 1, product_type_id: 20)
BarCode.create!(code: "7790202000658", amount: 1, product_type_id: 21)
BarCode.create!(code: "7790748235064", amount: 1, product_type_id: 22)
BarCode.create!(code: "7790261030016", amount: 1, product_type_id: 23)
BarCode.create!(code: "7790202000665", amount: 1, product_type_id: 24)
BarCode.create!(code: "7790202000221", amount: 1, product_type_id: 25)
BarCode.create!(code: "7790202000207", amount: 1, product_type_id: 26)
BarCode.create!(code: "7790580402907", amount: 1, product_type_id: 27)
BarCode.create!(code: "7790170904767", amount: 1, product_type_id: 28)
BarCode.create!(code: "7790261040008", amount: 1, product_type_id: 29)
BarCode.create!(code: "7796373002323", amount: 1, product_type_id: 30)
BarCode.create!(code: "7791113006395", amount: 1, product_type_id: 31)
BarCode.create!(code: "7794759000635", amount: 1, product_type_id: 32)
BarCode.create!(code: "7790580504601", amount: 1, product_type_id: 33)
BarCode.create!(code: "7791113006401", amount: 1, product_type_id: 34)
BarCode.create!(code: "7790150695944", amount: 1, product_type_id: 35)
BarCode.create!(code: "7793360112379", amount: 1, product_type_id: 36)
BarCode.create!(code: "7792180001528", amount: 1, product_type_id: 37)
BarCode.create!(code: "7792590000159", amount: 1, product_type_id: 38)
BarCode.create!(code: "7790070506924", amount: 1, product_type_id: 39)
BarCode.create!(code: "7790036007717", amount: 1, product_type_id: 40)
BarCode.create!(code: "7792378002238", amount: 1, product_type_id: 41)
BarCode.create!(code: "7792378002221", amount: 1, product_type_id: 42)
BarCode.create!(code: "7796373195704", amount: 1, product_type_id: 43)
BarCode.create!(code: "7792280000193", amount: 1, product_type_id: 44)
BarCode.create!(code: "7793360674105", amount: 1, product_type_id: 45)
BarCode.create!(code: "7790748235187", amount: 1, product_type_id: 46)
BarCode.create!(code: "7790261082015", amount: 1, product_type_id: 47)
BarCode.create!(code: "7790202000085", amount: 1, product_type_id: 48)
BarCode.create!(code: "7790748235149", amount: 1, product_type_id: 49)
BarCode.create!(code: "7798003220428", amount: 1, product_type_id: 50)
BarCode.create!(code: "7790580509309", amount: 1, product_type_id: 51)
BarCode.create!(code: "7793046008415", amount: 1, product_type_id: 52)
BarCode.create!(code: "7790580511302", amount: 1, product_type_id: 53)
BarCode.create!(code: "7798128560492", amount: 1, product_type_id: 54)
BarCode.create!(code: "7798128560676", amount: 1, product_type_id: 55)
BarCode.create!(code: "7798128560522", amount: 1, product_type_id: 56)
BarCode.create!(code: "7798128560706", amount: 1, product_type_id: 57)
BarCode.create!(code: "7796373291000", amount: 1, product_type_id: 58)
BarCode.create!(code: "7796373002385", amount: 1, product_type_id: 59)
BarCode.create!(code: "7793890001082", amount: 1, product_type_id: 60)
BarCode.create!(code: "7793890000979", amount: 1, product_type_id: 61)
BarCode.create!(code: "7793890001174", amount: 1, product_type_id: 62)
BarCode.create!(code: "7793890001150", amount: 1, product_type_id: 63)
BarCode.create!(code: "7792180004758", amount: 1, product_type_id: 64)
BarCode.create!(code: "7792590003198", amount: 1, product_type_id: 65)
BarCode.create!(code: "7796373002767", amount: 1, product_type_id: 66)
BarCode.create!(code: "7798004720026", amount: 1, product_type_id: 67)
BarCode.create!(code: "7798004720088", amount: 1, product_type_id: 68)
BarCode.create!(code: "7790580538002", amount: 1, product_type_id: 69)
BarCode.create!(code: "7790036008868", amount: 1, product_type_id: 70)
BarCode.create!(code: "7791579061082", amount: 1, product_type_id: 71)
BarCode.create!(code: "7794759000994", amount: 1, product_type_id: 72)
BarCode.create!(code: "7792900092683", amount: 1, product_type_id: 73)
BarCode.create!(code: "7792900009124", amount: 1, product_type_id: 74)
BarCode.create!(code: "7796373001425", amount: 1, product_type_id: 75)
BarCode.create!(code: "7796373001432", amount: 1, product_type_id: 76)
BarCode.create!(code: "7796373001449", amount: 1, product_type_id: 77)
BarCode.create!(code: "7796373001456", amount: 1, product_type_id: 78)
BarCode.create!(code: "7790036002675", amount: 1, product_type_id: 79)
BarCode.create!(code: "7790036002682", amount: 1, product_type_id: 80)
BarCode.create!(code: "7793360927508", amount: 1, product_type_id: 81)
BarCode.create!(code: "7796373290508", amount: 1, product_type_id: 82)
BarCode.create!(code: "7790411000142", amount: 1, product_type_id: 83)
BarCode.create!(code: "7792378000814", amount: 1, product_type_id: 84)
BarCode.create!(code: "7796373000084", amount: 1, product_type_id: 85)
BarCode.create!(code: "7792710000243", amount: 1, product_type_id: 86)
BarCode.create!(code: "7790387015119", amount: 1, product_type_id: 87)
BarCode.create!(code: "7792710000014", amount: 1, product_type_id: 88)
BarCode.create!(code: "7790802000027", amount: 1, product_type_id: 89)
BarCode.create!(code: "7790411000210", amount: 1, product_type_id: 90)
BarCode.create!(code: "7790480089390", amount: 1, product_type_id: 91)
BarCode.create!(code: "7790480089383", amount: 1, product_type_id: 92)
BarCode.create!(code: "7790387013511", amount: 1, product_type_id: 93)
BarCode.create!(code: "7790411001545", amount: 1, product_type_id: 94)
BarCode.create!(code: "7790070506696", amount: 1, product_type_id: 95)
BarCode.create!(code: "7790802000164", amount: 1, product_type_id: 96)
BarCode.create!(code: "7790895009679", amount: 1, product_type_id: 97)
BarCode.create!(code: "7790895003882", amount: 1, product_type_id: 98)
BarCode.create!(code: "7790895000119", amount: 1, product_type_id: 99)
BarCode.create!(code: "7790895006555", amount: 1, product_type_id: 100)
BarCode.create!(code: "7790639002416", amount: 1, product_type_id: 101)
BarCode.create!(code: "7790639002478", amount: 1, product_type_id: 104)
BarCode.create!(code: "7790639002430", amount: 1, product_type_id: 105)
BarCode.create!(code: "7790036002118", amount: 1, product_type_id: 107)
BarCode.create!(code: "7790036002156", amount: 1, product_type_id: 108)
BarCode.create!(code: "7790036002125", amount: 1, product_type_id: 109)
BarCode.create!(code: "7790036002194", amount: 1, product_type_id: 110)
BarCode.create!(code: "7790036002170", amount: 1, product_type_id: 111)
BarCode.create!(code: "7790036002187", amount: 1, product_type_id: 112)
BarCode.create!(code: "7794000792548", amount: 1, product_type_id: 113)
BarCode.create!(code: "7790895067556", amount: 1, product_type_id: 114)
BarCode.create!(code: "7790639001983", amount: 1, product_type_id: 115)
BarCode.create!(code: "7790639001976", amount: 1, product_type_id: 116)
BarCode.create!(code: "7790639001662", amount: 1, product_type_id: 117)
BarCode.create!(code: "7790639001365", amount: 1, product_type_id: 118)
BarCode.create!(code: "7790895002304", amount: 1, product_type_id: 119)
BarCode.create!(code: "7791813421153", amount: 1, product_type_id: 120)
BarCode.create!(code: "7790036004617", amount: 1, product_type_id: 121)
BarCode.create!(code: "7790036004600", amount: 1, product_type_id: 122)
BarCode.create!(code: "7790036004587", amount: 1, product_type_id: 123)
BarCode.create!(code: "7791813421351", amount: 1, product_type_id: 124)
BarCode.create!(code: "7790895064173", amount: 1, product_type_id: 125)
BarCode.create!(code: "7790036005317", amount: 1, product_type_id: 126)
BarCode.create!(code: "7790036004952", amount: 1, product_type_id: 127)
BarCode.create!(code: "7790036002613", amount: 1, product_type_id: 128)
BarCode.create!(code: "7790036004976", amount: 1, product_type_id: 129)
BarCode.create!(code: "7790036002644", amount: 1, product_type_id: 130)
BarCode.create!(code: "7790036004945", amount: 1, product_type_id: 131)
BarCode.create!(code: "7790036002620", amount: 1, product_type_id: 132)
BarCode.create!(code: "7793360106033", amount: 1, product_type_id: 133)
BarCode.create!(code: "7790895000898", amount: 1, product_type_id: 134)
BarCode.create!(code: "7798125810422", amount: 1, product_type_id: 135)
BarCode.create!(code: "7798125810446", amount: 1, product_type_id: 136)
BarCode.create!(code: "7798125810439", amount: 1, product_type_id: 137)
BarCode.create!(code: "7798125810361", amount: 1, product_type_id: 138)
BarCode.create!(code: "7798125810354", amount: 1, product_type_id: 139)
BarCode.create!(code: "7798125810347", amount: 1, product_type_id: 140)
BarCode.create!(code: "7798125810408", amount: 1, product_type_id: 141)
BarCode.create!(code: "7622300847210", amount: 1, product_type_id: 142)
BarCode.create!(code: "7790040333901", amount: 1, product_type_id: 143)
BarCode.create!(code: "7790263110969", amount: 1, product_type_id: 144)
BarCode.create!(code: "7798125810415", amount: 1, product_type_id: 145)
BarCode.create!(code: "7790263111041", amount: 1, product_type_id: 146)
BarCode.create!(code: "7790263111034", amount: 1, product_type_id: 147)
BarCode.create!(code: "7790263110709", amount: 1, product_type_id: 148)
BarCode.create!(code: "7790040174801", amount: 1, product_type_id: 149)
BarCode.create!(code: "7790040177505", amount: 1, product_type_id: 150)
BarCode.create!(code: "7792180008053", amount: 1, product_type_id: 151)
BarCode.create!(code: "7792180008022", amount: 1, product_type_id: 152)
BarCode.create!(code: "7792180008039", amount: 1, product_type_id: 153)
BarCode.create!(code: "7792180008046", amount: 1, product_type_id: 154)
BarCode.create!(code: "7798111060961", amount: 1, product_type_id: 155)
BarCode.create!(code: "7798111060299", amount: 1, product_type_id: 156)
BarCode.create!(code: "7790036008059", amount: 1, product_type_id: 157)
BarCode.create!(code: "7791337031517", amount: 1, product_type_id: 158)
BarCode.create!(code: "7791337915817", amount: 1, product_type_id: 159)
BarCode.create!(code: "7791337531567", amount: 1, product_type_id: 160)
BarCode.create!(code: "7790787087334", amount: 1, product_type_id: 161)
BarCode.create!(code: "7790787087341", amount: 1, product_type_id: 162)
BarCode.create!(code: "7791337832015", amount: 1, product_type_id: 163)
BarCode.create!(code: "7798111061227", amount: 1, product_type_id: 164)
BarCode.create!(code: "7798111061234", amount: 1, product_type_id: 165)
BarCode.create!(code: "7790036948348", amount: 1, product_type_id: 166)
BarCode.create!(code: "7790036005324", amount: 1, product_type_id: 167)
BarCode.create!(code: "7613034798602", amount: 1, product_type_id: 168)
BarCode.create!(code: "7794396004645", amount: 1, product_type_id: 169)
BarCode.create!(code: "7790036007465", amount: 1, product_type_id: 170)
BarCode.create!(code: "7790036007489", amount: 1, product_type_id: 171)
BarCode.create!(code: "7790080037357", amount: 1, product_type_id: 172)
BarCode.create!(code: "7790080044171", amount: 1, product_type_id: 173)
BarCode.create!(code: "7790036008035", amount: 1, product_type_id: 174)
BarCode.create!(code: "7790036008042", amount: 1, product_type_id: 175)
BarCode.create!(code: "7798095170823", amount: 1, product_type_id: 176)
BarCode.create!(code: "7791241000432", amount: 1, product_type_id: 177)
BarCode.create!(code: "7790036005508", amount: 1, product_type_id: 178)
BarCode.create!(code: "7790080032604", amount: 1, product_type_id: 179)
BarCode.create!(code: "7790080037135", amount: 1, product_type_id: 180)
BarCode.create!(code: "7794710010017", amount: 1, product_type_id: 181)
BarCode.create!(code: "7790080032611", amount: 1, product_type_id: 183)
BarCode.create!(code: "7790080037159", amount: 1, product_type_id: 184)
BarCode.create!(code: "7791337526075", amount: 1, product_type_id: 185)
BarCode.create!(code: "7790080040913", amount: 1, product_type_id: 186)
BarCode.create!(code: "7791337046078", amount: 1, product_type_id: 187)
BarCode.create!(code: "7790080040906", amount: 1, product_type_id: 188)
BarCode.create!(code: "7790080040890", amount: 1, product_type_id: 189)
BarCode.create!(code: "7791337046016", amount: 1, product_type_id: 190)
BarCode.create!(code: "7790080040876", amount: 1, product_type_id: 191)
BarCode.create!(code: "7791337526068", amount: 1, product_type_id: 192)
BarCode.create!(code: "7790080040920", amount: 1, product_type_id: 193)
BarCode.create!(code: "7798111061340", amount: 1, product_type_id: 194)
BarCode.create!(code: "7798111060916", amount: 1, product_type_id: 195)
BarCode.create!(code: "7790080040074", amount: 1, product_type_id: 196)
BarCode.create!(code: "7791337011311", amount: 1, product_type_id: 197)
BarCode.create!(code: "7791337011304", amount: 1, product_type_id: 198)
BarCode.create!(code: "7798111061548", amount: 1, product_type_id: 199)
BarCode.create!(code: "7794396000760", amount: 1, product_type_id: 200)
BarCode.create!(code: "7794396001057", amount: 1, product_type_id: 201)
BarCode.create!(code: "7790080014846", amount: 1, product_type_id: 202)
BarCode.create!(code: "7790080026078", amount: 1, product_type_id: 203)
BarCode.create!(code: "7794710070103", amount: 1, product_type_id: 204)
BarCode.create!(code: "7790080018882", amount: 1, product_type_id: 205)
BarCode.create!(code: "7794820003787", amount: 1, product_type_id: 211)
BarCode.create!(code: "7790080067958", amount: 1, product_type_id: 212)
BarCode.create!(code: "7791337933286", amount: 1, product_type_id: 213)
BarCode.create!(code: "7794820001653", amount: 1, product_type_id: 214)
BarCode.create!(code: "7790080067965", amount: 1, product_type_id: 215)
BarCode.create!(code: "7790080067910", amount: 1, product_type_id: 216)
BarCode.create!(code: "7798111060862", amount: 1, product_type_id: 217)
BarCode.create!(code: "7790080065312", amount: 1, product_type_id: 218)
BarCode.create!(code: "7790080065305", amount: 1, product_type_id: 220)
BarCode.create!(code: "7798111060879", amount: 1, product_type_id: 221)
BarCode.create!(code: "7794396000487", amount: 1, product_type_id: 222)
BarCode.create!(code: "7794396000180", amount: 1, product_type_id: 223)
BarCode.create!(code: "7791337533325", amount: 1, product_type_id: 224)
BarCode.create!(code: "7794396000999", amount: 1, product_type_id: 226)
BarCode.create!(code: "7791337533318", amount: 1, product_type_id: 227)
BarCode.create!(code: "7794396000197", amount: 1, product_type_id: 228)
BarCode.create!(code: "7790787104772", amount: 1, product_type_id: 230)
BarCode.create!(code: "7798138552364", amount: 1, product_type_id: 232)
BarCode.create!(code: "7798138552326", amount: 1, product_type_id: 236)
BarCode.create!(code: "7792550700440", amount: 1, product_type_id: 237)
BarCode.create!(code: "7791110001874", amount: 1, product_type_id: 238)
BarCode.create!(code: "7792180004963", amount: 1, product_type_id: 239)
BarCode.create!(code: "7797470005477", amount: 1, product_type_id: 240)
BarCode.create!(code: "7792180004949", amount: 1, product_type_id: 241)
BarCode.create!(code: "7797470003121", amount: 1, product_type_id: 242)
BarCode.create!(code: "7798138552340", amount: 1, product_type_id: 243)
BarCode.create!(code: "7792550700556", amount: 1, product_type_id: 244)
BarCode.create!(code: "7790236000105", amount: 1, product_type_id: 245)
BarCode.create!(code: "7790070320292", amount: 1, product_type_id: 247)
BarCode.create!(code: "7791110003069", amount: 1, product_type_id: 248)
BarCode.create!(code: "7790236001287", amount: 1, product_type_id: 251)
BarCode.create!(code: "7793890001563", amount: 1, product_type_id: 252)
user = User.create!(email: 'manager@proyectoalimentar.org', password: 'password', password_confirmation: 'password', manager: true)
StorageUnit.all.each { |s| s.managers << user; s.save!}
